### PR TITLE
Bg fix tests

### PR DESCRIPTION
**Pull request by faid-terence**
#### What does this PR do?
This pull request adds unit tests to ensure that all routes in the application are functioning correctly. By doing so, we can catch any regressions that may occur as we continue to develop and maintain the application.
#### Description of Task to be completed?
Ensure all Tests are Passing and Working as expected!

`git clone branch bg-fix-tests`
`run npm install`
`run npm run test`

#### What are the relevant pivotal tracker/Trello stories?
https://trello.com/c/BSYZqNeI/12-predator-ecommerce-app-qa
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by ALVINdimpos — APPROVED** [review]

**Review by yobuir — APPROVED** [review]

**Review by bryan936M — APPROVED** [review]
Good work!

**Review by chanceDira — CHANGES_REQUESTED** [review]
Can you fix the tests

**Review by Muhet — APPROVED** [review]
well done

**Review by Muhet — CHANGES_REQUESTED** [review]
Test in CI CD are not passing. Can you fix that?

**Review by chanceDira — APPROVED** [review]
Nice work @faid-terence

**Review by Muhet — APPROVED** [review]
Greate job faid

**Pull request merged**
