### PR TITLE
#2 feature: create payment processing endpoint

### PR DESCRIPTION
**Pull request by bryan936M**
#### What does this PR do?
- add STRIPE payment capability to the project
#### Description of Task to be completed?
- All inputs should be validated for sanity
- The payment confirmation should include all order details, including the order number, total cost, and expected delivery date
- The order status should be updated in the database and frontend to reflect the payment.
- Make sure that the Stripe API key is kept secure and not exposed in the backend code
- In the backend, use the Stripe library to make the payment, charge the customer and verify it.
#### How should this be manually tested?
- Download this repo locally
- Open it and run 'npm run dev'
- create an order(log in, add products to cart, checkout)
- input token of buyer in the 'authorization-header' and run this path 'http://localhost:3000/api/pay/order/'
- copy the URL into the browser
- fill in the data
- for card details use: 4242 4242 4242 4242
- the press the 'pay' button
#### Any background context you want to provide?
- This uses the STRIPE API for processing payments
#### What are the relevant pivotal tracker/Trello stories?
Trello card: https://trello.com/c/GvCh1rv1
#### Questions:

### CODE REVIEW

**Comment by bryan936M** [comment]
[Buyer should be able to make a payment](https://trello.com/c/GvCh1rv1/2-buyer-should-be-able-to-make-a-payment)

**Review by ALVINdimpos — APPROVED** [review]

**Review by vanessa-abewe — APPROVED** [review]

**Review by faid-terence — APPROVED** [review]
Nice Work

**Review by NTElissa — APPROVED** [review]
good progress

**Review by Muhet — APPROVED** [review]

**Review by chanceDira — APPROVED** [review]
Nice work

**Review by chanceDira — APPROVED** [review]
Good job @bryan936M

**Review by chanceDira — APPROVED** [review]
Nice job @bryan936M

**Pull request merged**
