### PR TITLE
# 19 Feature: add to cart

### PR DESCRIPTION
**Pull request by yobuir**
### What does this PR do?
Guest/Buyer should be able to add items to their cart

### Description of Task to be completed?
A guest or a buyer should be able to add an items to the cart, including storing the cart in the buyer's account and calculating the new cart total.

#### Having these endpoints working 
`[ POST /api/cart ]`

What are the relevant pivotal tracker/Trello stories?
Trello Card : https://trello.com/c/v2IUlmMO/19-guest-buyer-should-be-able-to-add-items-to-their-cart

### How should this be manually tested

- clone the repo
- install all dependencies
- get auth Token [`POST   /api/login`]
- use postman or Thunder Client to test the endpoint [`POST /api/cart`]

Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by ALVINdimpos — APPROVED** [review]

**Review by faid-terence — APPROVED** [review]
Good Work @yobuir

**Review by nili-alu — APPROVED** [review]
nice job, but you have many commit message better if you swatch them

**Review by vanessa-abewe — APPROVED** [review]

**Review by Muhet — APPROVED** [review]
well done but try to reduce number of commit

**Review by chanceDira — APPROVED** [review]
Awesome 👍🏽, 
Just again you commit messages, you squash them

**Review by bryan936M — APPROVED** [review]

**Review by NTElissa — COMMENTED** [review]
good progress but squash those commit  message

**Comment by yobuir** [comment]
> Awesome 👍🏽, Just again you commit messages, you squash them

fixed

**Pull request merged**
