### PR TITLE
#7 Read update order status feature

### PR DESCRIPTION
**Pull request by Muhet**
### What does this PR do?
Guest/Buyer should be able to read/retrieve his or her status order.
Admin should be able to update the order status .

### Description of Task to be completed?
A guest or a buyer should be able to read/retrieve his/her order status that he/she ordered including  status if it is pending , delivered or consoled plus reason why it censored, product information, billing information and the total amount that he paid.

Admin should be able to update the status of ordered item so that a buyer should keep track on his/ he product.

#### Having these endpoints working 
`[ GET /api/status/:orderId ]`
`[ PATCH /api/status/:orderId ]`

What are the relevant pivotal tracker/Trello stories?
Trello Card :https://trello.com/c/H9UdP2Ra/7-read-and-update-the-order-status
### How should this be manually tested

- clone the repo
- install all dependencies `[ npm install ]`
- get auth Token [ `POST   /api/login` ]
- You need to obtain productId from  [ ` GET api/product ` ] 
- use postman or Thunder Client to test the endpoint [ ` GET /api/status/:orderId}` ] , [ `  PATCH /api/status/:orderId ` ]

Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by nili-alu — APPROVED** [review]
great

**Review by NTElissa — APPROVED** [review]
good work

**Review by NTElissa — COMMENTED** [review]
you have some conflict  from develop , solve it before to be marg

**Review by ALVINdimpos — APPROVED** [review]

**Review by vanessa-abewe — APPROVED** [review]

**Review by chanceDira — APPROVED** [review]
Good work @Muhet

**Pull request merged**
